### ISSUE TITLE
Message.php syntax error in php 5.5.30

### ISSUE THREAD

**Issue by iwzh** [ElfSundae/bearychat#4]
syntax error, unexpected '|', expecting ')' 
![image](https://user-images.githubusercontent.com/9714125/39300584-c5a68764-497e-11e8-9e1c-2318e84da146.png)

![image](https://user-images.githubusercontent.com/9714125/39300719-4228d666-497f-11e8-9a4b-362f7f59237c.png)

**Comment by ElfSundae** [comment]
感谢反馈。应该是 PHP 5.5 语法不兼容，我晚点更新下这个包。

**Comment by ElfSundae** [comment]
dropped support for PHP < 5.6  5fa8cabbf6e760101495a724646f7b2f83af61fd
